[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# solc_version = '0.8.18'
auto_detect_solc = true

[fmt]
ignore = ['lib', 'src/lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
